name: Call Packer
on: 
  push:
    paths: 
      - ".github/workflows/packer.yml"
      - "gce/*.hcl"
      - "gce/*.sh"

jobs:
  packer-build:
          uses: RachitGupta008/packer-pipeline/.github/workflows/packer.yml@main
          with: 
              build-path: 'gce'
          secrets: inherit
  
