name: Call Packer
on: 
  push:
    paths: "gce/*.hcl"

jobs:
  packer-build:
          uses: RachitGupta008/packer-pipeline/.github/workflows/packer.yml@main
          with: 
              build-path: 'gce'
          secrets: inherit
  
