name: Call Packer
on: 
   workflow_dispatch:

jobs:
  packer-build:
                  # Add "id-token" with the intended permissions.
          permissions:
            contents: 'read'
            id-token: 'write'
          uses: RachitGupta008/packer-pipeline/.github/workflows/packer.yml@main
          with: 
              build-path: 'gce'
          secrets: inherit
  
