name: Call Packer
on: 
   workflow_dispatch:

jobs:
  packer-build:
          uses: RachitGupta008/packer-pipeline/.github/workflows/packer.yml@main
          with: 
              build-path: 'gce'
          secrets: inherit
  
