name: Call Packer
on: [push]

jobs:
  packer-build:
          uses: RachitGupta008/packer-pipeline/.github/workflows/packer.yml@main
          with: 
              build-path: 'hello'
          secrets: inherit
  
