name: Delete Zombie

on: [push]


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Delete Zombie VMs
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: List all VMs in the project
      run: |
        while read -r line; do
          instance_name=$(echo $line | cut -d ',' -f1)
          zone=$(echo $line | cut -d ',' -f2)
          gcloud compute instances describe $instance_name --zone=zone
        done < <(gcloud compute instances list --format="csv(name, zone)" --filter="name~'packer.*' AND status=RUNNING AND lastStartTimestamp<$(date -u -Iseconds -d '1 mins ago')" | tail -1)
        

