name: Delete Zombie

on: [push]


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Delete Zombie VMs
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

    - name: List all VMs in the project
      run: |
        gcloud compute instances list --format="table(name,zone,status,disks.deviceName,uptimeSeconds)" --filter="status=RUNNING AND uptimeSeconds>7200" > all_vms.txt
        cat all_vms.txt
        

