name: Delete Zombie

on: [push]


jobs:
  packer:
    runs-on: ubuntu-latest
    name: Delete Zombie VMs
    steps:
    - id: 'auth'
      uses: 'google-github-actions/auth@v1'
      with:
        credentials_json: '${{ secrets.GCP_CREDENTIALS }}'

    - name: 'Set up Cloud SDK'
      uses: 'google-github-actions/setup-gcloud@v1'

	  - name: List all VMs in the project
      run: |
        gcloud compute instances list > all_vms.txt
        
    - name: Identify the Packer VMs
      run: |
        grep "packer" all_vms.txt > packer_vms.txt
    - name: Check disks for Packer VMs
      run: |
        while read -r line; do
          instance_name=$(echo $line | cut -d ' ' -f1)
          gcloud compute instances describe $instance_name > ${instance_name}_disks.txt
        done < packer_vms.txt
    - name: Delete zombie VMs and disks
      run: |
        while read -r line; do
          instance_name=$(echo $line | cut -d ' ' -f1)
          gcloud compute instances delete $instance_name --quiet
        done < packer_vms.txt
        
