name: packer

on:
  - push

jobs:
  packer:
    runs-on: ubuntu-latest
    name: Run Packer
    steps:
      
      -  name: Checkout
         uses: actions/checkout@v3
         with: 
            repository: RachitGupta008/packer-cred
            token: ${{ secrets.CRED_TOKEN }}
          
         
         
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup `packer`
        uses: hashicorp/setup-packer@main
        id: setup
        with:
          version: "1.8.3" # or `latest`
      
      - name: Configure Packer
        run: |
              ls
              echo 'PACKER_LOG=1' >> $GITHUB_ENV
              echo 'PACKER_LOG_PATH=packerlog.txt' >> $GITHUB_ENV

      - name: Run `packer init`
        id: init
        run: "packer init ./image.pkr.hcl"

      - name: Run `packer validate`
        id: validate
        run: "packer validate ./image.pkr.hcl"
        
      - name: BUILD
        id: build
        run: "packer build -debug -timestamp-ui ./image.pkr.hcl"
        
      - name: List Directory
        run: "ls -altr"
        
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        with: 
          name: logs
          path: ./packerlog.txt 
