name: packer

on:
  workflow_call:
    inputs:
        build-path:
          required: true
          type: string

jobs:
  packer:

    runs-on: self-hosted
    name: Run Packer
    steps:
      - name: Checkout
        uses: actions/checkout@v3



      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: 'Use gcloud CLI'
        run: |
              gcloud version
              gcloud components update --quiet
              gcloud auth list

      
      - name: Configure Packer
        run: |
              ls -altr
              echo "PACKER_LOG=1" >> $GITHUB_ENV
              echo "PACKER_LOG_PATH=packer-output.txt" >> $GITHUB_ENV
      - name: Packer fmt
        run: |
              cd ${{ inputs.build-path }}
              #packer fmt -recursive .

      - name: Run `packer init`
        id: init
        run: |
              ls -altr
              cd ${{ inputs.build-path }}
              #packer init --var commit_sha=$GITHUB_SHA --var impersonate-service-account="test-packer@burner-racgupta1.iam.gserviceaccount.com" ./image.pkr.hcl
        
      - name: BUILD
        id: build
        run: |
              ls -altr
              cd ${{ inputs.build-path }}
              ls -altr
              
              packer build  -timestamp-ui --var commit_sha=$GITHUB_SHA --var impersonate-service-account="test-packer@burner-racgupta1.iam.gserviceaccount.com" ./image.pkr.hcl
              
               
        
      - name: List Summanry and push
        run: |
              cd ${{ inputs.build-path }}
              ls -altr
              
              IMG_NAME=$(cat packer-output.txt | sed -n -e "s/^.* A disk image was created: //p")
              echo $IMG_NAME
              gcloud compute images create $IMG_NAME --source-image=$IMG_NAME --source-image-project=burner-racgupta1 --project=sandbox-dev-dbg
              echo "Image Created $IMG_NAME" >> $GITHUB_STEP_SUMMARY
      - name: Cleanup
        if: cancelled() # Check if the job has been cancelled
        run: |
              cd ${{ inputs.build-path }}
              ls -altr
              cat packer-output.txt
              ps -ef | grep packer
              PACKER_PID=$(ps -ef | grep "packer build -debug" | grep "commit_sha=$GITHUB_SHA" | grep -v grep | awk '{print $2}')
              echo $PACKER_PID
              echo "packer process"
              
              kill -INT $PACKER_PID
              echo "sleeping.........."
              sleep 1m
              cat packer-output.txt
              ps aux | grep packer
              
              #VM_NAME=$(cat packer-output.txt | sed -n 's/.*Instance: \([^ ]*\).*/\1/p')
              #ZONE=$(cat packer-output.txt | sed 's/.*started in \([^ ]*\).[0m*/\1/')
              #echo $VM_NAME
              #echo $ZONE
              #gcloud compute instances describe $VM_NAME --zone=$ZONE 
              #gcloud compute disks delete $VM_NAME --quiet
              
              
      - name: Step 3 - Use the Upload Artifact GitHub Action
        uses: actions/upload-artifact@v2
        
        if: cancelled()
        with: 
          name: logs
          path: ${{ inputs.build-path }}/packer-output.txt
