name: Reusable Workflow
on:
  workflow_call:
    inputs:
      environment:
        description: 'Environment for the job'
        required: true
        type: string


jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run a one-line script
        run: echo Hello, world!
